services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /app/tmp
      - ./db/migrations:/app/migrations
    command: air
    depends_on:
      - db
    environment:
      - DSN=workuser:Passw0rd!@tcp(db:3306)/go_blog_db?parseTime=true&autocommit=0&sql_mode='TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY'

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=go_blog_db
      - MYSQL_USER=workuser
      - MYSQL_PASSWORD=Passw0rd!
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --skip-character-set-client-handshake
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-data:
    driver: local
